[module/calendar]
type = custom/script
exec = TZ='Europe/Paris' python3 -u ~/.scripts/uni/countdown.py
; click-left = qutebrowser 'https://calendar.google.com/calendar/' -- &
click-left = google-calendar-dark
tail = true

format-background = ${colors.color2}
format-foreground = ${colors.color0}
format-padding = 1
