[module/updates]
type = custom/script
exec = $HOME/.config/polybar/scripts/updates.sh
tail = false
interval = 120

; format-prefix = " "
; format-prefix-foreground = ${colors.fg}
format-background = ${colors.grey-9}
format-foreground = ${colors.pink-a2}

