[module/xmonad]
type = custom/script
exec = $HOME/.config/polybar/scripts/xmonad-log

tail = true

format-background = ${colors.color2}
format-foreground = ${colors.color0}
; format-focused-background = ${colors.grey-9}
; format-focused-foreground = ${colors.yellow-a4}
; format-focused-padding = 1

; format-occupied-background = ${colors.grey-9}
; format-occupied-foreground = ${colors.light-blue-a4}
; format-occupied-padding = 1

; format-urgent-background = ${colors.grey-9}
; format-urgent-foreground = ${colors.red-a4}
; format-urgent-padding = 1

; format-empty-background = ${colors.grey-9}
; format-empty-foreground = ${colors.indigo-a4}
; format-empty-padding = 1
