[module/xworkspaces]
type = internal/xworkspaces

format = <label-state>
format-padding = 1
format-background = ${colors.grey-9}

label-monitor = %name%

label-active = %name%
; label-active = %{T4}%icon%%{T-}
label-active-foreground = ${colors.pink-a4}
; label-active-background = ${colors.blue-a1}
label-active-padding = 1

label-occupied = %name%
; label-occupied = %{T4}%icon%%{T-}
label-occupied-foreground = ${colors.pink-a1}
; label-occupied-background = ${colors.grey-9}
label-occupied-padding = 1

label-urgent = %name%
; label-urgent = %{T4}%icon%%{T-}
label-urgent-foreground = ${colors.red-a4}
; label-urgent-background = ${colors.grey-9}
label-urgent-padding = 1

label-empty = %name%
; label-empty = %{T4}%icon%%{T-}
label-empty-foreground = ${colors.fg}
; label-empty-background = ${colors.grey-9}
label-empty-padding = 1
