import = ["/home/yann/.cache/wal/colors-alacritty.toml"]

[env]
EDITOR = "vim"
LANG = "en_US.utf8"
LC_CTYPE = "en_US.utf8"
SHELL = "/usr/bin/zsh"
TERM = "alacritty"

[font]
size = 8.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[scrolling]
history = 10000

[window]
opacity = 0.8
