#!/bin/zsh

if [ "$(pgrep -cx polybar)" -gt 0 ]; then
    echo "The panel is running. Stopping it"
    pkill -nx "polybar"
    sleep 2
    while [ "$(pgrep -cx polybar)" -gt 0 ]; do
        pkill -nx -9 "polybar"
    done
fi

export MONITOR="$(xrandr -q | rg "connected primary" | cut -d' ' -f1)"
# polybar example -c $(dirname $0)/config.bkp &
polybar main -c $HOME/.config/polybar/config.ini &

sleep 0.5
# Order matters. If tray is below polybar clicks will be picked up by polybar
# and not the tray icons underneath
xdo lower -n tray
xdo lower -n polybar
wait
