#+TITLE: vimrc config
#+AUTHOR: Edwin Elminster (eldwinster)
#+STARTUP: showeverything
:PROPERTIES:
:header-args: :tangle .vimrc
:END:

* vimrc
** General
*** Sets how many lines of history VIM has to remember

#+begin_src conf
set history=500
#+end_src

*** Enable filetype plugins

#+begin_src conf
filetype plugin on
filetype indent on
filetype off
#+end_src

*** Set to auto read when a file is changed from the outside

#+begin_src conf
set autoread
au FocusGained,BufEnter * checktime
#+end_src

*** be viMproved, required

#+begin_src conf
set nocompatible
set encoding=utf-8
#+end_src

*** set the runtime path to include Vundle and initialize

#+begin_src conf
set rtp+=~/.vim/bundle/Vundle.vim
set rtp+=~/university/current_course
#+end_src

*** With a map leader it's possible to do extra key combinations like <leader>w saves the current file

#+begin_src conf
let mapleader = ","
#+end_src

*** Fast saving

#+begin_src conf
nmap <leader>w :w!<cr>
#+end_src

*** Fast editing and reloading of vimrc configs

#+begin_src conf
map <leader>e :e! ~/.vimrc<cr>
autocmd! bufwritepost ~/.vimrc source ~/.vimrc
#+end_src

*** :W sudo saves the file (useful for handling the permission-denied error)

#+begin_src conf
command! W execute 'w !sudo tee % > /dev/null' <bar> edit!
#+end_src

*** Turn on persistent undo on means that you can undo even when you close a buffer/VIM

#+begin_src conf
try
    set undodir=~/.vim_runtime/temp_dirs/undodir
    set undofile
catch
endtry
#+end_src

*** Source vimrc

#+begin_src conf
map <C-s> :source ~/.vimrc<CR>
#+end_src

*** Update snippet

#+begin_src conf
map <C-c> :call UltiSnips#RefreshSnippets()<CR>
#+end_src

** Vundle
 This is required, all plugins must appear after this line.

*** Plugins description

| Name                 | Description                                                                                      | remarks                                                                                                                                      |
|----------------------+--------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------|
| Vundle               | plugins manager                                                                                  |                                                                                                                                              |
| vimtex               | latex compiler                                                                                   |                                                                                                                                              |
| ultisnips            | snippets plugins                                                                                 |                                                                                                                                              |
| vim-snippets         | snippets examples                                                                                |                                                                                                                                              |
| tex-conceal          | conceal latex syntax                                                                             | use the mathematicals symbols                                                                                                                |
| wal                  | colorscheme                                                                                      |                                                                                                                                              |
| vim-css-color        | css-color preview                                                                                |                                                                                                                                              |
| vifm                 | vim like file manager                                                                            | I'm not sure wheather it workds                                                                                                              |
| ack                  | grep like tool                                                                                   | plugin for the silver_searcher (ag) or ack --a wicked fast grep (not sur it works)                                                           |
| bufexplorer          | buff manager                                                                                     | quickly and easily switch between buffers. This plugin can be opened with <leader+o>                                                         |
| lightline            | a light and configurable statusline/tabline                                                      |                                                                                                                                              |
| nerdtree             | a tree explorer                                                                                  |                                                                                                                                              |
| vim-commentary       | Comment stuff out                                                                                | Use gcc to comment out a line (takes a count), gc to comment out the target of a motion. gcu to uncomments a set of adjacent commented lines |
| vim-expand-region    | Allows you to visually select increasingly larger regions of text using the same key combination |                                                                                                                                              |
| vim-fugitive         | git wrapper                                                                                      |                                                                                                                                              |
| vim-indent-object    | defines a new text object representing lines of code at the same indent level                    |                                                                                                                                              |
| vim-multiple-cursors | Sublime text style multiple selections for vim, ^N is remapped to ^s (due to YankRing)           |                                                                                                                                              |
| vim-yankstack        | Maintains a history of previous yanks, changes and deletes                                       |                                                                                                                                              |
| vim-obsession        | save sessions                                                                                    |                                                                                                                                              |

*** Plugins

#+begin_src conf
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'lervag/vimtex'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'KeitaNakamura/tex-conceal.vim'
Plugin 'dylanaraps/wal'
Plugin 'ap/vim-css-color'
"Plugin 'vifm/vifm.vim'
Plugin 'mileszs/ack.vim'
Plugin 'vim-scripts/bufexplorer.zip'
" Plugin 'itchyny/lightline.vim'
Plugin 'preservim/nerdtree'
Plugin 'tpope/vim-commentary'
Plugin 'terryma/vim-expand-region'
Plugin 'tpope/vim-fugitive'
Plugin 'michaeljsmith/vim-indent-object'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'maxbrunsfeld/vim-yankstack'
Plugin 'tpope/vim-obsession'
call vundle#end()
#+end_src

** VIM user interface
*** Set 7 lines to the cursor - when moving vertically using j/k

#+begin_src conf
set so=7
set t_Co=256
#+end_src

*** Turn on the Wild menu

#+begin_src conf
set wildmenu
#+end_src

*** Ignore compiled files

#+begin_src conf
set wildignore=*.o,*~,*.pyc
if has("win16") || has("win32")
    set wildignore+=.git\*,.hg\*,.svn\*
else
    set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store
endif
#+end_src

*** Always show current position

#+begin_src conf
set ruler
#+end_src

*** Height of the command bar

#+begin_src conf
set cmdheight=1
#+end_src

*** A buffer becomes hidden when it is abandoned

#+begin_src conf
set hid
#+end_src

*** Configure backspace so it acts as it should act

#+begin_src conf
set backspace=eol,start,indent
set whichwrap+=<,>,h,l
#+end_src

*** Ignore case when searching

#+begin_src conf
set ignorecase
#+end_src

*** When searching try to be smart about cases

#+begin_src conf
set smartcase
#+end_src

*** Highlight search results

#+begin_src conf
set hlsearch
#+end_src

*** Makes search act like search in modern browsers

#+begin_src conf
set incsearch
#+end_src

*** Don't redraw while executing macros (good performance config)

#+begin_src conf
set lazyredraw
#+end_src

*** For regular expressions turn magic on

#+begin_src conf
set magic
#+end_src

*** Show matching brackets when text indicator is over them

#+begin_src conf
set showmatch
#+end_src

*** How many tenths of a second to blink when matching brackets

#+begin_src conf
set mat=2
#+end_src

*** Add a bit extra margin to the left

#+begin_src conf
set foldcolumn=1
#+end_src

** Colors and Fonts
*** Enable syntax highlighting

#+begin_src conf
syntax enable
#+end_src

*** colorscheme

#+begin_src conf
colorscheme wal
set background=dark
#+end_src

*** Set utf8 as standard encoding and en_US as the standard language

#+begin_src conf
set encoding=utf8
#+end_src

*** Use Unix as the standard file type

#+begin_src conf
set ffs=unix,dos,mac
#+end_src

*** allow vim-css-color to work after copying the after/syntax to ~/.vim/ for css-color-folder

#+begin_src conf
syntax enable
#+end_src
** Files, backups and undo
*** Turn backup off, since most stuff is in SVN, git etc. anyway...

#+begin_src conf
set nobackup
set nowb
set noswapfile
#+end_src

** Text, tab and indent related

*** Use spaces instead of tabs

#+begin_src conf
set expandtab
#+end_src

*** Be smart when using tabs ;)

#+begin_src conf
set smarttab
#+end_src

*** 1 tab == 4 spaces

#+begin_src conf
set shiftwidth=4
set tabstop=4
#+end_src

*** Linebreak on 500 characters

#+begin_src conf
set lbr
set tw=500
#+end_src

*** Indent

#+begin_src conf
set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines
#+end_src
** Visual mode related

*** Visual mode pressing * or # searches for the current selection super useful! From an idea by Michael Naumann

#+begin_src conf
vnoremap <silent> * :<C-u>call VisualSelection('', '')<CR>/<C-R>=@/<CR><CR>
vnoremap <silent> # :<C-u>call VisualSelection('', '')<CR>?<C-R>=@/<CR><CR>
#+end_src

** Command mode related

*** Smart mappings on the command line

#+begin_src conf
cno $h e ~/
cno $d e ~/Desktop/
cno $j e ./
cno $c e <C-\>eCurrentFileDir("e")<cr>
#+end_src

*** $q is super useful when browsing on the command line it deletes everything until the last slash

#+begin_src conf
cno $q <C-\>eDeleteTillSlash()<cr>
#+end_src

*** Bash like keys for the command line

#+begin_src conf
cnoremap <C-A>		<Home>
cnoremap <C-E>		<End>
cnoremap <C-K>		<C-U>
cnoremap <C-P> <Up>
cnoremap <C-N> <Down>
#+end_src

** Moving around, tabs, windows and buffers

*** Map <Space> to / (search) and Ctrl-<Space> to ? (backwards search)

#+begin_src conf
map <space> /
map <C-space> ?
#+end_src

*** Disable highlight when <leader><cr> is pressed

#+begin_src conf
map <silent> <leader><cr> :noh<cr>
#+end_src

*** Smart way to move between windows

#+begin_src conf
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
#+end_src

*** Close the current buffer

#+begin_src conf
map <leader>bd :Bclose<cr>:tabclose<cr>gT
#+end_src

*** Close all the buffers

#+begin_src conf
map <leader>ba :bufdo bd<cr>
map <leader>l :bnext<cr>
map <leader>h :bprevious<cr>
#+end_src

*** Useful mappings for managing tabs

#+begin_src conf
map <leader>tn :tabnew<cr>
map <leader>to :tabonly<cr>
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove
map <leader>t<leader> :tabnext
#+end_src

*** Let 'tl' toggle between this and the last accessed tab

#+begin_src conf
let g:lasttab = 1
nmap <Leader>tl :exe "tabn ".g:lasttab<CR>
au TabLeave * let g:lasttab = tabpagenr()
#+end_src


*** Opens a new tab with the current buffer's path super useful when editing files in the same directory

#+begin_src conf
map <leader>te :tabedit <C-r>=expand("%:p:h")<cr>/
#+end_src

*** Switch CWD to the directory of the open buffer

#+begin_src conf
map <leader>cd :cd %:p:h<cr>:pwd<cr>
#+end_src

*** Specify the behavior when switching between buffers

#+begin_src conf
try
  set switchbuf=useopen,usetab,newtab
  set stal=2
catch
endtry
#+end_src

*** Return to last edit position when opening files (You want this!)

#+begin_src conf
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
#+end_src
** Status line

*** Always show the status line

#+begin_src conf
set laststatus=2
#+end_src

*** Format the status line

#+begin_src conf
set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l\ \ Column:\ %c
#+end_src

*** relative number on the left

#+begin_src conf
set relativenumber
#+end_src

** Editing mappings
*** Remap VIM 0 to first non-blank character

#+begin_src conf
map 0 ^
#+end_src

*** Move a line of text using ALT+[jk] or Command+[jk] on mac

#+begin_src conf
nmap <M-j> mz:m+<cr>`z
nmap <M-k> mz:m-2<cr>`z
vmap <M-j> :m'>+<cr>`<my`>mzgv`yo`z
vmap <M-k> :m'<-2<cr>`>my`<mzgv`yo`z

if has("mac") || has("macunix")
  nmap <D-j> <M-j>
  nmap <D-k> <M-k>
  vmap <D-j> <M-j>
  vmap <D-k> <M-k>
endif
#+end_src

*** Delete trailing white space on save, useful for some filetypes ;)

#+begin_src conf
fun! CleanExtraSpaces()
    let save_cursor = getpos(".")
    let old_query = getreg('/')
    silent! %s/\s\+$//e
    call setpos('.', save_cursor)
    call setreg('/', old_query)
endfun

if has("autocmd")
    autocmd BufWritePre *.txt,*.js,*.py,*.wiki,*.sh,*.coffee :call CleanExtraSpaces()
endif
#+end_src

** Ack searching and cope displaying
Requires ack.vim - it's much better than vimgrep/grep

*** Use the the_silver_searcher if possible (much faster than Ack)

#+begin_src conf
if executable('ag')
  let g:ackprg = 'ag --vimgrep --smart-case'
endif
#+end_src

*** When you press gv you Ack after the selected text

#+begin_src conf
vnoremap <silent> gv :call VisualSelection('gv', '')<CR>
#+end_src

*** Open Ack and put the cursor in the right position

#+begin_src conf
map <leader>g :Ack
#+end_src

*** When you press <leader>r you can search and replace the selected text

#+begin_src conf
vnoremap <silent> <leader>r :call VisualSelection('replace', '')<CR>
#+end_src

*** Do :help cope if you are unsure what cope is. It's super useful!

- When you search with Ack, display your results in cope by doing:
  <leader>cc

- To go to the next search result do:
  <leader>n

- To go to the previous search results do:
  <leader>p

#+begin_src conf
map <leader>cc :botright cope<cr>
map <leader>co ggVGy:tabnew<cr>:set syntax=qf<cr>pgg
map <leader>n :cn<cr>
map <leader>p :cp<cr>
#+end_src

*** Make sure that enter is never overriden in the quickfix window

#+begin_src conf
autocmd BufReadPost quickfix nnoremap <buffer> <CR> <CR>
#+end_src

** Spell checking

*** Pressing ,ss will toggle and untoggle spell checking

#+begin_src conf
map <leader>ss :setlocal spell!<cr>
#+end_src

*** Activate spell check

#+begin_src conf
map <leader>b :set spelllang=fr<CR>
map <C-b> :set spelllang=en_gb<CR>
#+end_src

*** Pressing ^l will correct misspell

#+begin_src conf
inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u
#+end_src

*** Enable spell checking
setlocal spell
set spelllang=fr,en_gb

#+begin_src conf
set spelllang=fr
#+end_src

*** Shortcuts using <leader>

#+begin_src conf
map <leader>sn ]s
map <leader>sp [s
map <leader>sa zg
map <leader>s? z=
#+end_src

** Misc

*** Remove the Windows ^M - when the encodings gets messed up

#+begin_src conf
noremap <Leader>m mmHmt:%s/<C-V><cr>//ge<cr>'tzt'm
#+end_src

*** Quickly open a buffer for scribble

#+begin_src conf
map <leader>q :e ~/buffer<cr>
#+end_src

*** Quickly open a markdown buffer for scribble

#+begin_src conf
map <leader>x :e ~/buffer.md<cr>
#+end_src

*** Toggle paste mode on and off

#+begin_src conf
map <leader>pp :setlocal paste!<cr>
#+end_src

*** Parenthesis/bracket

#+begin_src conf
vnoremap $1 <esc>`>a)<esc>`<i(<esc>
vnoremap $2 <esc>`>a]<esc>`<i[<esc>
vnoremap $3 <esc>`>a}<esc>`<i{<esc>
vnoremap $$ <esc>`>a"<esc>`<i"<esc>
vnoremap $q <esc>`>a'<esc>`<i'<esc>
vnoremap $e <esc>`>a`<esc>`<i`<esc>
#+end_src

*** Map auto complete of (, ", ', [

#+begin_src conf
inoremap $1 ()<esc>i
inoremap $2 []<esc>i
inoremap $3 {}<esc>i
inoremap $4 {<esc>o}<esc>O
inoremap $q ''<esc>i
inoremap $e ""<esc>i
#+end_src

** Helper functions

*** Returns true if paste mode is enabled

#+begin_src conf
function! HasPaste()
    if &paste
        return 'PASTE MODE  '
    endif
    return ''
endfunction
#+end_src

*** Don't close window, when deleting a buffer

#+begin_src conf
command! Bclose call <SID>BufcloseCloseIt()
function! <SID>BufcloseCloseIt()
    let l:currentBufNum = bufnr("%")
    let l:alternateBufNum = bufnr("#")

    if buflisted(l:alternateBufNum)
        buffer #
    else
        bnext
    endif
#+end_src

*** Others functions

#+begin_src conf
    if bufnr("%") == l:currentBufNum
        new
    endif

    if buflisted(l:currentBufNum)
        execute("bdelete! ".l:currentBufNum)
    endif
endfunction

function! CmdLine(str)
    call feedkeys(":" . a:str)
endfunction

function! VisualSelection(direction, extra_filter) range
    let l:saved_reg = @"
    execute "normal! vgvy"

    let l:pattern = escape(@", "\\/.*'$^~[]")
    let l:pattern = substitute(l:pattern, "\n$", "", "")

    if a:direction == 'gv'
        call CmdLine("Ack '" . l:pattern . "' " )
    elseif a:direction == 'replace'
        call CmdLine("%s" . '/'. l:pattern . '/')
    endif

    let @/ = l:pattern
    let @" = l:saved_reg
endfunction

func! DeleteTillSlash()
    let g:cmd = getcmdline()

    if has("win16") || has("win32")
        let g:cmd_edited = substitute(g:cmd, "\\(.*\[\\\\]\\).*", "\\1", "")
    else
        let g:cmd_edited = substitute(g:cmd, "\\(.*\[/\]\\).*", "\\1", "")
    endif

    if g:cmd == g:cmd_edited
        if has("win16") || has("win32")
            let g:cmd_edited = substitute(g:cmd, "\\(.*\[\\\\\]\\).*\[\\\\\]", "\\1", "")
        else
            let g:cmd_edited = substitute(g:cmd, "\\(.*\[/\]\\).*/", "\\1", "")
        endif
    endif

    return g:cmd_edited
endfunc

func! CurrentFileDir(cmd)
    return a:cmd . " " . expand("%:p:h") . "/"
endfunc
#+end_src
** Plugin config

*** vimtex

#+begin_src conf
let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
inoremap <C-f> <Esc>: silent exec '.!inkscape-figures create "'.getline('.').'" "'.b:vimtex.root.'/figures/"'<CR><CR>:w<CR>
nnoremap <C-f> : silent exec '!inkscape-figures edit "'.b:vimtex.root.'/figures/" > /dev/null 2>&1 &'<CR><CR>:redraw!<CR>
#+end_src

*** ultisnips

#+begin_src conf
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
#+end_src

*** tex-conceal

#+begin_src conf
set conceallevel=1
let g:tex_conceal='abdmg'
hi Conceal ctermbg=none
#+end_src

*** bufExplorer

#+begin_src conf
let g:bufExplorerDefaultHelp=0
let g:bufExplorerShowRelativePath=1
let g:bufExplorerFindActive=1
let g:bufExplorerSortBy='name'
map <leader>o :BufExplorer<cr>
#+end_src

*** YankStack

#+begin_src conf
let g:yankstack_yank_keys = ['y', 'd']

nmap <C-p> <Plug>yankstack_substitute_older_paste
nmap <C-n> <Plug>yankstack_substitute_newer_paste
#+end_src

*** Nerd Tree

#+begin_src conf
let g:NERDTreeWinPos = "right"
let NERDTreeShowHidden=0
let NERDTreeIgnore = ['\.pyc$', '__pycache__']
let g:NERDTreeWinSize=35
map <leader>nn :NERDTreeToggle<cr>
map <leader>nb :NERDTreeFromBookmark<Space>
map <leader>nf :NERDTreeFind<cr>
#+end_src

*** vim-multiple-cursors

#+begin_src conf
let g:multi_cursor_use_default_mapping=0
#+end_src

- Default mapping

#+begin_src conf
let g:multi_cursor_start_word_key      = '<C-s>'
let g:multi_cursor_select_all_word_key = '<A-s>'
let g:multi_cursor_start_key           = 'g<C-s>'
let g:multi_cursor_select_all_key      = 'g<A-s>'
let g:multi_cursor_next_key            = '<C-s>'
let g:multi_cursor_prev_key            = '<C-p>'
let g:multi_cursor_skip_key            = '<C-x>'
let g:multi_cursor_quit_key            = '<Esc>'
#+end_src

*** lightline
#+begin_example
let g:lightline = {
      \ 'colorscheme': 'Tomorrow Night Blue',
      \ 'active': {
      \   'left': [ ['mode', 'paste'],
      \             ['fugitive', 'readonly', 'filename', 'modified'] ],
      \   'right': [ [ 'lineinfo' ], ['percent'] ]
      \ },
      \ 'component': {
      \   'readonly': '%{&filetype=="help"?"":&readonly?"🔒":""}',
      \   'modified': '%{&filetype=="help"?"":&modified?"+":&modifiable?"":"-"}',
      \   'fugitive': '%{exists("*FugitiveHead")?FugitiveHead():""}'
      \ },
      \ 'component_visible_condition': {
      \   'readonly': '(&filetype!="help"&& &readonly)',
      \   'modified': '(&filetype!="help"&&(&modified||!&modifiable))',
      \   'fugitive': '(exists("*FugitiveHead") && ""!=FugitiveHead())'
      \ },
      \ 'separator': { 'left': ' ', 'right': ' ' },
      \ 'subseparator': { 'left': ' ', 'right': ' ' }
      \ }
#+end_example
